---
- name: Install developer tools
  hosts: all
  become: True

  tasks:
    - name: Install Git
      yum:
        name: git
        state: latest

    - name: Install Docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Add Docker Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Add user to Docker group
      user:
        name: adrian
        groups: docker
        append: yes

    - name: Enable & Start Docker service
      service:
        name: docker
        state: started
        enabled: True

    - name: Add Microsoft repository
      yum_repository:
        name: code
        description: vscode
        file: vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        baseurl: https://packages.microsoft.com/yumrepos/vscode

    - name: Install vscode
      yum:
        name: code
        state: latest
