---
- name: Install developer tools
  hosts: all
  become: True

  tasks:
    - name: Install tools for Centos
      include: centos.yml
      when: ansible_distribution == 'CentOS'

    - name: Install tools for Ubuntu
      include: ubuntu.yml
      when: ansible_distribution == 'Ubuntu'